sudo: required
services:
  - docker

before_install:
  - docker build -t mooping/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mooping/react-test npm run test -- --coverage

after_success:
  - docker build -t mooping/multi-client ./client
  - docker build -t mooping/multi-nginx ./nginx
  - docker build -t mooping/multi-server ./server
  - docker build -t mooping/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push mooping/multi-client
  - docker push mooping/multi-nginx
  - docker push mooping/multi-server
  - docker push mooping/multi-worker